version: "3"

services:
  db:
    container_name: database
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  adminer:
    container_name: adminer
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
